/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccesRouteImport } from './routes/succes'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ProjetRouteImport } from './routes/projet'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactArtisanIdRouteImport } from './routes/contact-artisan.$id'
import { Route as ArtisanIdRouteImport } from './routes/artisan.$id'

const SuccesRoute = SuccesRouteImport.update({
  id: '/succes',
  path: '/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetRoute = ProjetRouteImport.update({
  id: '/projet',
  path: '/projet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactArtisanIdRoute = ContactArtisanIdRouteImport.update({
  id: '/contact-artisan/$id',
  path: '/contact-artisan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanIdRoute = ArtisanIdRouteImport.update({
  id: '/artisan/$id',
  path: '/artisan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projet': typeof ProjetRoute
  '/recherche': typeof RechercheRoute
  '/succes': typeof SuccesRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/contact-artisan/$id': typeof ContactArtisanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projet': typeof ProjetRoute
  '/recherche': typeof RechercheRoute
  '/succes': typeof SuccesRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/contact-artisan/$id': typeof ContactArtisanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projet': typeof ProjetRoute
  '/recherche': typeof RechercheRoute
  '/succes': typeof SuccesRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/contact-artisan/$id': typeof ContactArtisanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/projet'
    | '/recherche'
    | '/succes'
    | '/artisan/$id'
    | '/contact-artisan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/projet'
    | '/recherche'
    | '/succes'
    | '/artisan/$id'
    | '/contact-artisan/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/projet'
    | '/recherche'
    | '/succes'
    | '/artisan/$id'
    | '/contact-artisan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProjetRoute: typeof ProjetRoute
  RechercheRoute: typeof RechercheRoute
  SuccesRoute: typeof SuccesRoute
  ArtisanIdRoute: typeof ArtisanIdRoute
  ContactArtisanIdRoute: typeof ContactArtisanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/succes': {
      id: '/succes'
      path: '/succes'
      fullPath: '/succes'
      preLoaderRoute: typeof SuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projet': {
      id: '/projet'
      path: '/projet'
      fullPath: '/projet'
      preLoaderRoute: typeof ProjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-artisan/$id': {
      id: '/contact-artisan/$id'
      path: '/contact-artisan/$id'
      fullPath: '/contact-artisan/$id'
      preLoaderRoute: typeof ContactArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/$id': {
      id: '/artisan/$id'
      path: '/artisan/$id'
      fullPath: '/artisan/$id'
      preLoaderRoute: typeof ArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProjetRoute: ProjetRoute,
  RechercheRoute: RechercheRoute,
  SuccesRoute: SuccesRoute,
  ArtisanIdRoute: ArtisanIdRoute,
  ContactArtisanIdRoute: ContactArtisanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
