/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SuccesRouteImport } from './routes/succes'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ProjetRouteImport } from './routes/projet'
import { Route as MetiersRouteImport } from './routes/metiers'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactProRouteImport } from './routes/contact-pro'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AbonnementsRouteImport } from './routes/abonnements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifierEmailTokenRouteImport } from './routes/verifier-email.$token'
import { Route as SosMetierRouteImport } from './routes/sos.$metier'
import { Route as MetiersMetierRouteImport } from './routes/metiers.$metier'
import { Route as ContactArtisanIdRouteImport } from './routes/contact-artisan.$id'
import { Route as ArtisanMetierRouteImport } from './routes/artisan.$metier'
import { Route as ArtisanIdRouteImport } from './routes/artisan.$id'
import { Route as SosMetierCommuneRouteImport } from './routes/sos.$metier.$commune'
import { Route as ArtisanMetierCommuneRouteImport } from './routes/artisan.$metier.$commune'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccesRoute = SuccesRouteImport.update({
  id: '/succes',
  path: '/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetRoute = ProjetRouteImport.update({
  id: '/projet',
  path: '/projet',
  getParentRoute: () => rootRouteImport,
} as any)
const MetiersRoute = MetiersRouteImport.update({
  id: '/metiers',
  path: '/metiers',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactProRoute = ContactProRouteImport.update({
  id: '/contact-pro',
  path: '/contact-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementsRoute = AbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierEmailTokenRoute = VerifierEmailTokenRouteImport.update({
  id: '/verifier-email/$token',
  path: '/verifier-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SosMetierRoute = SosMetierRouteImport.update({
  id: '/$metier',
  path: '/$metier',
  getParentRoute: () => SosRoute,
} as any)
const MetiersMetierRoute = MetiersMetierRouteImport.update({
  id: '/$metier',
  path: '/$metier',
  getParentRoute: () => MetiersRoute,
} as any)
const ContactArtisanIdRoute = ContactArtisanIdRouteImport.update({
  id: '/contact-artisan/$id',
  path: '/contact-artisan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanMetierRoute = ArtisanMetierRouteImport.update({
  id: '/artisan/$metier',
  path: '/artisan/$metier',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanIdRoute = ArtisanIdRouteImport.update({
  id: '/artisan/$id',
  path: '/artisan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SosMetierCommuneRoute = SosMetierCommuneRouteImport.update({
  id: '/$commune',
  path: '/$commune',
  getParentRoute: () => SosMetierRoute,
} as any)
const ArtisanMetierCommuneRoute = ArtisanMetierCommuneRouteImport.update({
  id: '/$commune',
  path: '/$commune',
  getParentRoute: () => ArtisanMetierRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/contact-pro': typeof ContactProRoute
  '/dashboard': typeof DashboardRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/metiers': typeof MetiersRouteWithChildren
  '/projet': typeof ProjetRoute
  '/recherche': typeof RechercheRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRouteWithChildren
  '/succes': typeof SuccesRoute
  '/tarifs': typeof TarifsRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/artisan/$metier': typeof ArtisanMetierRouteWithChildren
  '/contact-artisan/$id': typeof ContactArtisanIdRoute
  '/metiers/$metier': typeof MetiersMetierRoute
  '/sos/$metier': typeof SosMetierRouteWithChildren
  '/verifier-email/$token': typeof VerifierEmailTokenRoute
  '/artisan/$metier/$commune': typeof ArtisanMetierCommuneRoute
  '/sos/$metier/$commune': typeof SosMetierCommuneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/contact-pro': typeof ContactProRoute
  '/dashboard': typeof DashboardRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/metiers': typeof MetiersRouteWithChildren
  '/projet': typeof ProjetRoute
  '/recherche': typeof RechercheRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRouteWithChildren
  '/succes': typeof SuccesRoute
  '/tarifs': typeof TarifsRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/artisan/$metier': typeof ArtisanMetierRouteWithChildren
  '/contact-artisan/$id': typeof ContactArtisanIdRoute
  '/metiers/$metier': typeof MetiersMetierRoute
  '/sos/$metier': typeof SosMetierRouteWithChildren
  '/verifier-email/$token': typeof VerifierEmailTokenRoute
  '/artisan/$metier/$commune': typeof ArtisanMetierCommuneRoute
  '/sos/$metier/$commune': typeof SosMetierCommuneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/contact-pro': typeof ContactProRoute
  '/dashboard': typeof DashboardRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/metiers': typeof MetiersRouteWithChildren
  '/projet': typeof ProjetRoute
  '/recherche': typeof RechercheRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRouteWithChildren
  '/succes': typeof SuccesRoute
  '/tarifs': typeof TarifsRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/artisan/$metier': typeof ArtisanMetierRouteWithChildren
  '/contact-artisan/$id': typeof ContactArtisanIdRoute
  '/metiers/$metier': typeof MetiersMetierRoute
  '/sos/$metier': typeof SosMetierRouteWithChildren
  '/verifier-email/$token': typeof VerifierEmailTokenRoute
  '/artisan/$metier/$commune': typeof ArtisanMetierCommuneRoute
  '/sos/$metier/$commune': typeof SosMetierCommuneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnements'
    | '/admin'
    | '/auth'
    | '/cgu'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/contact'
    | '/contact-pro'
    | '/dashboard'
    | '/mentions-legales'
    | '/metiers'
    | '/projet'
    | '/recherche'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sos'
    | '/succes'
    | '/tarifs'
    | '/artisan/$id'
    | '/artisan/$metier'
    | '/contact-artisan/$id'
    | '/metiers/$metier'
    | '/sos/$metier'
    | '/verifier-email/$token'
    | '/artisan/$metier/$commune'
    | '/sos/$metier/$commune'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnements'
    | '/admin'
    | '/auth'
    | '/cgu'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/contact'
    | '/contact-pro'
    | '/dashboard'
    | '/mentions-legales'
    | '/metiers'
    | '/projet'
    | '/recherche'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sos'
    | '/succes'
    | '/tarifs'
    | '/artisan/$id'
    | '/artisan/$metier'
    | '/contact-artisan/$id'
    | '/metiers/$metier'
    | '/sos/$metier'
    | '/verifier-email/$token'
    | '/artisan/$metier/$commune'
    | '/sos/$metier/$commune'
  id:
    | '__root__'
    | '/'
    | '/abonnements'
    | '/admin'
    | '/auth'
    | '/cgu'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/contact'
    | '/contact-pro'
    | '/dashboard'
    | '/mentions-legales'
    | '/metiers'
    | '/projet'
    | '/recherche'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sos'
    | '/succes'
    | '/tarifs'
    | '/artisan/$id'
    | '/artisan/$metier'
    | '/contact-artisan/$id'
    | '/metiers/$metier'
    | '/sos/$metier'
    | '/verifier-email/$token'
    | '/artisan/$metier/$commune'
    | '/sos/$metier/$commune'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementsRoute: typeof AbonnementsRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CguRoute: typeof CguRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  ContactProRoute: typeof ContactProRoute
  DashboardRoute: typeof DashboardRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MetiersRoute: typeof MetiersRouteWithChildren
  ProjetRoute: typeof ProjetRoute
  RechercheRoute: typeof RechercheRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SosRoute: typeof SosRouteWithChildren
  SuccesRoute: typeof SuccesRoute
  TarifsRoute: typeof TarifsRoute
  ArtisanIdRoute: typeof ArtisanIdRoute
  ArtisanMetierRoute: typeof ArtisanMetierRouteWithChildren
  ContactArtisanIdRoute: typeof ContactArtisanIdRoute
  VerifierEmailTokenRoute: typeof VerifierEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/succes': {
      id: '/succes'
      path: '/succes'
      fullPath: '/succes'
      preLoaderRoute: typeof SuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projet': {
      id: '/projet'
      path: '/projet'
      fullPath: '/projet'
      preLoaderRoute: typeof ProjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metiers': {
      id: '/metiers'
      path: '/metiers'
      fullPath: '/metiers'
      preLoaderRoute: typeof MetiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-pro': {
      id: '/contact-pro'
      path: '/contact-pro'
      fullPath: '/contact-pro'
      preLoaderRoute: typeof ContactProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnements': {
      id: '/abonnements'
      path: '/abonnements'
      fullPath: '/abonnements'
      preLoaderRoute: typeof AbonnementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier-email/$token': {
      id: '/verifier-email/$token'
      path: '/verifier-email/$token'
      fullPath: '/verifier-email/$token'
      preLoaderRoute: typeof VerifierEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos/$metier': {
      id: '/sos/$metier'
      path: '/$metier'
      fullPath: '/sos/$metier'
      preLoaderRoute: typeof SosMetierRouteImport
      parentRoute: typeof SosRoute
    }
    '/metiers/$metier': {
      id: '/metiers/$metier'
      path: '/$metier'
      fullPath: '/metiers/$metier'
      preLoaderRoute: typeof MetiersMetierRouteImport
      parentRoute: typeof MetiersRoute
    }
    '/contact-artisan/$id': {
      id: '/contact-artisan/$id'
      path: '/contact-artisan/$id'
      fullPath: '/contact-artisan/$id'
      preLoaderRoute: typeof ContactArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/$metier': {
      id: '/artisan/$metier'
      path: '/artisan/$metier'
      fullPath: '/artisan/$metier'
      preLoaderRoute: typeof ArtisanMetierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/$id': {
      id: '/artisan/$id'
      path: '/artisan/$id'
      fullPath: '/artisan/$id'
      preLoaderRoute: typeof ArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos/$metier/$commune': {
      id: '/sos/$metier/$commune'
      path: '/$commune'
      fullPath: '/sos/$metier/$commune'
      preLoaderRoute: typeof SosMetierCommuneRouteImport
      parentRoute: typeof SosMetierRoute
    }
    '/artisan/$metier/$commune': {
      id: '/artisan/$metier/$commune'
      path: '/$commune'
      fullPath: '/artisan/$metier/$commune'
      preLoaderRoute: typeof ArtisanMetierCommuneRouteImport
      parentRoute: typeof ArtisanMetierRoute
    }
  }
}

interface MetiersRouteChildren {
  MetiersMetierRoute: typeof MetiersMetierRoute
}

const MetiersRouteChildren: MetiersRouteChildren = {
  MetiersMetierRoute: MetiersMetierRoute,
}

const MetiersRouteWithChildren =
  MetiersRoute._addFileChildren(MetiersRouteChildren)

interface SosMetierRouteChildren {
  SosMetierCommuneRoute: typeof SosMetierCommuneRoute
}

const SosMetierRouteChildren: SosMetierRouteChildren = {
  SosMetierCommuneRoute: SosMetierCommuneRoute,
}

const SosMetierRouteWithChildren = SosMetierRoute._addFileChildren(
  SosMetierRouteChildren,
)

interface SosRouteChildren {
  SosMetierRoute: typeof SosMetierRouteWithChildren
}

const SosRouteChildren: SosRouteChildren = {
  SosMetierRoute: SosMetierRouteWithChildren,
}

const SosRouteWithChildren = SosRoute._addFileChildren(SosRouteChildren)

interface ArtisanMetierRouteChildren {
  ArtisanMetierCommuneRoute: typeof ArtisanMetierCommuneRoute
}

const ArtisanMetierRouteChildren: ArtisanMetierRouteChildren = {
  ArtisanMetierCommuneRoute: ArtisanMetierCommuneRoute,
}

const ArtisanMetierRouteWithChildren = ArtisanMetierRoute._addFileChildren(
  ArtisanMetierRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementsRoute: AbonnementsRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CguRoute: CguRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  ContactProRoute: ContactProRoute,
  DashboardRoute: DashboardRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MetiersRoute: MetiersRouteWithChildren,
  ProjetRoute: ProjetRoute,
  RechercheRoute: RechercheRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SosRoute: SosRouteWithChildren,
  SuccesRoute: SuccesRoute,
  TarifsRoute: TarifsRoute,
  ArtisanIdRoute: ArtisanIdRoute,
  ArtisanMetierRoute: ArtisanMetierRouteWithChildren,
  ContactArtisanIdRoute: ContactArtisanIdRoute,
  VerifierEmailTokenRoute: VerifierEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
