/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SuccesRouteImport } from './routes/succes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ProjetRouteImport } from './routes/projet'
import { Route as MetiersRouteImport } from './routes/metiers'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifierEmailTokenRouteImport } from './routes/verifier-email.$token'
import { Route as ContactArtisanIdRouteImport } from './routes/contact-artisan.$id'
import { Route as ArtisanMetierRouteImport } from './routes/artisan.$metier'
import { Route as ArtisanIdRouteImport } from './routes/artisan.$id'
import { Route as ArtisanMetierCommuneRouteImport } from './routes/artisan.$metier.$commune'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccesRoute = SuccesRouteImport.update({
  id: '/succes',
  path: '/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetRoute = ProjetRouteImport.update({
  id: '/projet',
  path: '/projet',
  getParentRoute: () => rootRouteImport,
} as any)
const MetiersRoute = MetiersRouteImport.update({
  id: '/metiers',
  path: '/metiers',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierEmailTokenRoute = VerifierEmailTokenRouteImport.update({
  id: '/verifier-email/$token',
  path: '/verifier-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactArtisanIdRoute = ContactArtisanIdRouteImport.update({
  id: '/contact-artisan/$id',
  path: '/contact-artisan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanMetierRoute = ArtisanMetierRouteImport.update({
  id: '/artisan/$metier',
  path: '/artisan/$metier',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanIdRoute = ArtisanIdRouteImport.update({
  id: '/artisan/$id',
  path: '/artisan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanMetierCommuneRoute = ArtisanMetierCommuneRouteImport.update({
  id: '/$commune',
  path: '/$commune',
  getParentRoute: () => ArtisanMetierRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/metiers': typeof MetiersRoute
  '/projet': typeof ProjetRoute
  '/recherche': typeof RechercheRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/succes': typeof SuccesRoute
  '/tarifs': typeof TarifsRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/artisan/$metier': typeof ArtisanMetierRouteWithChildren
  '/contact-artisan/$id': typeof ContactArtisanIdRoute
  '/verifier-email/$token': typeof VerifierEmailTokenRoute
  '/artisan/$metier/$commune': typeof ArtisanMetierCommuneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/metiers': typeof MetiersRoute
  '/projet': typeof ProjetRoute
  '/recherche': typeof RechercheRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/succes': typeof SuccesRoute
  '/tarifs': typeof TarifsRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/artisan/$metier': typeof ArtisanMetierRouteWithChildren
  '/contact-artisan/$id': typeof ContactArtisanIdRoute
  '/verifier-email/$token': typeof VerifierEmailTokenRoute
  '/artisan/$metier/$commune': typeof ArtisanMetierCommuneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/metiers': typeof MetiersRoute
  '/projet': typeof ProjetRoute
  '/recherche': typeof RechercheRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/succes': typeof SuccesRoute
  '/tarifs': typeof TarifsRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/artisan/$metier': typeof ArtisanMetierRouteWithChildren
  '/contact-artisan/$id': typeof ContactArtisanIdRoute
  '/verifier-email/$token': typeof VerifierEmailTokenRoute
  '/artisan/$metier/$commune': typeof ArtisanMetierCommuneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cgu'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/contact'
    | '/dashboard'
    | '/mentions-legales'
    | '/metiers'
    | '/projet'
    | '/recherche'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/succes'
    | '/tarifs'
    | '/artisan/$id'
    | '/artisan/$metier'
    | '/contact-artisan/$id'
    | '/verifier-email/$token'
    | '/artisan/$metier/$commune'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cgu'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/contact'
    | '/dashboard'
    | '/mentions-legales'
    | '/metiers'
    | '/projet'
    | '/recherche'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/succes'
    | '/tarifs'
    | '/artisan/$id'
    | '/artisan/$metier'
    | '/contact-artisan/$id'
    | '/verifier-email/$token'
    | '/artisan/$metier/$commune'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cgu'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/contact'
    | '/dashboard'
    | '/mentions-legales'
    | '/metiers'
    | '/projet'
    | '/recherche'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/succes'
    | '/tarifs'
    | '/artisan/$id'
    | '/artisan/$metier'
    | '/contact-artisan/$id'
    | '/verifier-email/$token'
    | '/artisan/$metier/$commune'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CguRoute: typeof CguRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MetiersRoute: typeof MetiersRoute
  ProjetRoute: typeof ProjetRoute
  RechercheRoute: typeof RechercheRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccesRoute: typeof SuccesRoute
  TarifsRoute: typeof TarifsRoute
  ArtisanIdRoute: typeof ArtisanIdRoute
  ArtisanMetierRoute: typeof ArtisanMetierRouteWithChildren
  ContactArtisanIdRoute: typeof ContactArtisanIdRoute
  VerifierEmailTokenRoute: typeof VerifierEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/succes': {
      id: '/succes'
      path: '/succes'
      fullPath: '/succes'
      preLoaderRoute: typeof SuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projet': {
      id: '/projet'
      path: '/projet'
      fullPath: '/projet'
      preLoaderRoute: typeof ProjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metiers': {
      id: '/metiers'
      path: '/metiers'
      fullPath: '/metiers'
      preLoaderRoute: typeof MetiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier-email/$token': {
      id: '/verifier-email/$token'
      path: '/verifier-email/$token'
      fullPath: '/verifier-email/$token'
      preLoaderRoute: typeof VerifierEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-artisan/$id': {
      id: '/contact-artisan/$id'
      path: '/contact-artisan/$id'
      fullPath: '/contact-artisan/$id'
      preLoaderRoute: typeof ContactArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/$metier': {
      id: '/artisan/$metier'
      path: '/artisan/$metier'
      fullPath: '/artisan/$metier'
      preLoaderRoute: typeof ArtisanMetierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/$id': {
      id: '/artisan/$id'
      path: '/artisan/$id'
      fullPath: '/artisan/$id'
      preLoaderRoute: typeof ArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/$metier/$commune': {
      id: '/artisan/$metier/$commune'
      path: '/$commune'
      fullPath: '/artisan/$metier/$commune'
      preLoaderRoute: typeof ArtisanMetierCommuneRouteImport
      parentRoute: typeof ArtisanMetierRoute
    }
  }
}

interface ArtisanMetierRouteChildren {
  ArtisanMetierCommuneRoute: typeof ArtisanMetierCommuneRoute
}

const ArtisanMetierRouteChildren: ArtisanMetierRouteChildren = {
  ArtisanMetierCommuneRoute: ArtisanMetierCommuneRoute,
}

const ArtisanMetierRouteWithChildren = ArtisanMetierRoute._addFileChildren(
  ArtisanMetierRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CguRoute: CguRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MetiersRoute: MetiersRoute,
  ProjetRoute: ProjetRoute,
  RechercheRoute: RechercheRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccesRoute: SuccesRoute,
  TarifsRoute: TarifsRoute,
  ArtisanIdRoute: ArtisanIdRoute,
  ArtisanMetierRoute: ArtisanMetierRouteWithChildren,
  ContactArtisanIdRoute: ContactArtisanIdRoute,
  VerifierEmailTokenRoute: VerifierEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
